### ISSUE TITLE
Little issues in Login.vue Page

### ISSUE THREAD

**Issue by kevinmarrec** [mstaack/quasar-advanced-starter#11]
I found 2 issues on the Login.vue Page/Component

- Not being able to have leading/trailing spaces in password cause of `v-model.trim`
- Mistake about the `ref` name on the password input (should be 'password').

I fixed these 2 issues, I'm linking a PR to this really soon.

Kevin.

**Comment by kevinmarrec** [comment]
Updated the PR, to be able to have also the possibility to have leading/trailing spaces in the password when registering.

Btw I forgot to create a new branch but it should be fine ?

**Comment by mstaack** [comment]
thank you!
