### ISSUE TITLE
Cant get pass the login screen :/

### ISSUE THREAD

**Issue by xarkz** [mstaack/quasar-advanced-starter#14]
Hello, I download this demo for testing but I can't enter to the main app because of the broken login/session method.
The main errors are:
error.response is undefined

state.user is null

I tought it was a permission bug of the LocalStorage and I gave Admin Permission to Visual Studio Code but all remained the same...
I deleted all i could of the related session code but its imposible to acces to /news, white screen or the 404 page always apear.
Best regards, Toni.

**Comment by mstaack** [comment]
hey toni,

how are your backend routes looking?
You might have to adjust the api calls to your backend request & response format.

did you install all the quasar dependencies?

Cheers Max
